# @package _global_

defaults:
  - _self_
  - data: Cora  # 指定Cora数据集的配置
  - model: GRCN  # 指向GRCNModel的配置
  - callbacks: default
  - logger: tensorboard  # 使用TensorBoard进行日志记录
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train_grcn_cora"
tags: ["GRCN", "Cora"]
train: True
test: True
ckpt_path: null
seed: 42
